young_record/young_record/config/routes.rb
Rails.application.routes.draw do

  root to: 'items#top'
  resources :items, only: [:index, :show]
	
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  resource :admins, only: [:index]
  namespace :admins do
    resources :genre, only: [:index, :show]
    resources :histories, only: [:index, :show]
    resources :items, only: [:index, :new, :edit, :create]
    resources :users, only: [:index, :show]
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resource :users, only: [:index, :show]
  namespace :users do
    resources :carts, only: [:index]
    get 'carts/buy' => 'carts#buy'
    get 'carts/thanks' => 'carts#thanks'
    resources :histories, only: [:index, :show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

young_record/young_record/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

young_record/young_record/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

young_record/young_record/app/models/cart.rb
class Cart < ApplicationRecord
end

young_record/young_record/app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :item
	has_many :songs
	accepts_nested_attributes_for :songs
end

young_record/young_record/app/models/genre.rb
class Genre < ApplicationRecord
end

young_record/young_record/app/models/history.rb
class History < ApplicationRecord
end

young_record/young_record/app/models/history_item.rb
class HistoryItem < ApplicationRecord
end

young_record/young_record/app/models/item.rb
class Item < ApplicationRecord
	has_many :cds
	accepts_nested_attributes_for :cds
end

young_record/young_record/app/models/items_genre.rb
class ItemsGenre < ApplicationRecord
end

young_record/young_record/app/models/song.rb
class Song < ApplicationRecord
	belongs_to :cd
end

young_record/young_record/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

young_record/young_record/app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
	def index
		
	end
	def new
		@item = Item.new
		@item.cds.build.songs.build
	end
	def edit
		
	end
	def create
		item = Item.new(item_params)
		item.save
		redirect_to root_path
	end

	private
	def item_params
		params.require(:item).permit(:price, :count, :cd_number, :name, :artist_name, :label_name, :text_id, :frag,{
			cds_attributes: [:id, :name,{
				songs_attributes: [:id, :name]
			}]})
		
	end
end

young_record/young_record/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
		
	end
end

young_record/young_record/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?



   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name_char,
                               :name_kana,
                               :post,
                               :address,
                               :tell])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name_char,
                               :name_kana,
                               :post,
                               :address,
                               :tell])

  end
end

young_record/young_record/app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def top
		
	end
	def index
		
	end
	def show
		
	end
end

young_record/young_record/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		
	end
end

young_record/young_record/app/helpers/admins/genre_helper.rb
module Admins::GenreHelper
end

young_record/young_record/app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

young_record/young_record/app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

young_record/young_record/app/helpers/admins_helper.rb
module AdminsHelper
end

young_record/young_record/app/helpers/application_helper.rb
module ApplicationHelper
end

young_record/young_record/app/helpers/items_helper.rb
module ItemsHelper
end

young_record/young_record/app/helpers/users/carts_helper.rb
module Users::CartsHelper
end

young_record/young_record/app/helpers/users/histories_helper.rb
module Users::HistoriesHelper
end

young_record/young_record/app/helpers/users_helper.rb
module UsersHelper
end

young_record/young_record/app/views/items/index.html.erb
検索ページ

young_record/young_record/app/views/items/show.html.erb
商品詳細

young_record/young_record/app/views/items/top.html.erb
トップページ
<br><br>
<%= link_to 'root', root_path %><br>
<%= link_to 'item index', items_path %><br>
item show, item_path(id)<br>
<br>




<%= link_to 'admin sign in', new_admin_session_path %><br>
<%= link_to 'admin sign up', new_admin_registration_path %><br>
<%= link_to 'admin logout', destroy_admin_session_path, method: :delete %><br>
<br>


<%= link_to 'user sign in', new_user_session_path %><br>
<%= link_to 'user sign up', new_user_registration_path %><br>
<%= link_to ' logout', destroy_user_session_path, method: :delete %>
<%= link_to 'user mypage', users_path %><br>
退会確認ページ<br>
<br>

<%= link_to 'user history index', users_histories_path %><br>
show, users_history_path<br>
<br>

<%= link_to 'user cart index', users_carts_path %><br>
<%= link_to 'user cart buy', users_carts_buy_path %><br>
<%= link_to 'user cart thanks', users_carts_thanks_path %><br>
<br>
<%= link_to 'admin item index', admins_items_path %><br>
<%= link_to 'admin item new', new_admins_item_path %><br>
edit, edit_admins_item_path(id)<br>
<br>

<%= link_to 'admin user index', admins_users_path %><br>
show, admins_user_path(id)<br>
<br>

<%= link_to 'admin history index', admins_histories_path %><br>
show, admins_history_path(id)<br>
<br>

<%= link_to 'admin genre index', admins_genre_index_path %><br>
show, admins_genre_path(id)<br>
<br>