config/routes.rb
Rails.application.routes.draw do

  root to: 'items#top'
  resources :items, only: [:index, :show]
  post 'items' => 'items#index', as: 'items_search'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  get '/admins/index' => 'admins#index', as: 'admins_top'
  namespace :admins do
    resources :genre, only: [:index, :show, :create, :update]
    resources :histories, only: [:index, :show, :update]
    resources :items, only: [:index, :new, :edit, :create, :update]
    resources :users, only: [:index, :show]
    get 'items/:id/edit_cds' => 'items#edit_cds', as: 'edit_cds'
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resource :users, only: [:index, :show]
  namespace :users do
    resources :carts, only: [:index, :create, :destroy]
    get 'carts/buy' => 'carts#buy'
    get 'carts/thanks' => 'carts#thanks'
    resources :histories, only: [:index, :show, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :histories
  has_many :carts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	validates :name_char, presence: true,
				 format: {
				  with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/,
				  message: "漢字、カタカナ、ひらがなのみで入力して下さい"
				 }
	validates :name_kana, presence: true,
                 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }
	validates :email, presence: true
	validates :tell, presence: true
	validates :post, presence: true
	# validates :address, presence: true
	validates :address_prefecture, presence: true
	validates :address_city, presence: true
	validates :address_building, presence: true

	validates :post, format: { with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}$|^\d{5}$|^\d{7}\z/ }
	validates :tell, format: { with: /\A\d{10}$|^\d{11}\z/ }

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	before_action :authenticate_admin!
	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
		@histories = @user.histories
	end
end

app/controllers/users/carts_controller.rb
class Users::CartsController < ApplicationController
	before_action :authenticate_user!

	def index
		@carts = Cart.all
		@carts = current_user.carts
	end

	def buy
		
	end
	def thanks
		
	end
	def create
		item = Item.find(params[:item_id])
		if current_user.carts.exists?(item_id: item.id) then
			cart = current_user.carts.find_by(item_id: item.id)
			item.count -= params[:count][:count].to_i
			cart.count += params[:count][:count].to_i
			item.update(item_params)
			cart.update(cart_params)
		else
			cart = Cart.new
			cart.user_id = current_user.id
			cart.item_id = item.id
			item.count -= params[:count][:count].to_i
			cart.count = params[:count][:count].to_i
			item.update(item_params)
			cart.save
		end
		redirect_to users_carts_path
	end

	def destroy
		@cart = Cart.find(params[:id])
		@cart.destroy
		redirect_to users_carts_path
	end


	private
	def item_params
		params.permit(:count)
	end
	def cart_params
		params.permit(:count)
	end
end

app/controllers/users/histories_controller.rb
class Users::HistoriesController < ApplicationController
	def index
		@histories = current_user.histories
	end
	def show
		@history = History.find(params[:id])
	end

	def create
		# 履歴(history)の作成
		history = current_user.histories.new
		history.sum = 0
		history.user_address = current_user.address
		history.user_post = current_user.post
		history.save

		# 履歴の中身()history_items作成
		current_user.carts.each do |cart|
			# ひとつずつ作って保存を繰り返す
			h = history.history_items.new
			# カートの情報を移す
			h.item_id = cart.item_id
			h.cart_count = cart.count
			h.cart_price = cart.item.price
			h.save
			# sumに個数x値段を足す
			history.sum += (cart.item.price * cart.count)
			# 移し済みのカートを削除
			cart.destroy
		end
		# sumを変更したので更新
		history.update(history_params)

		redirect_to users_carts_thanks_path
	end

	private
	# sum更新用
	def history_params
		params.permit(:sum)
	end
end

app/views/admins/users/index.html.erb
<h2>ユーザー一覧</h2>

<table>
	<tr>
		<th>ID</th>
		<th>おなまえ（漢字</th>
		<th>おなまえ（カタカナ）</th>
		<th>メールアドレス</th>
		<th>携帯番号</th>
		<th>郵便番号</th>
		<th>都道府県</th>
		<th>住所</th>
		<th>建物</th>
	</tr>

	<% @users.each do |u| %>
	<tr>
		<td>
			<%= link_to u.id, admins_user_path(u) %>
		</td>
		<td>
			<%= link_to u.name_char, admins_user_path(u) %>
		</td>
		<td><%= u.name_kana %></td>
		<td><%= u.email %></td>
		<td><%= u.tell %></td>
		<td><%= u.post %></td>
		<td><%= u.address_prefecture %></td>
		<td><%= u.address_city %></td>
		<td><%= u.address_building %></td>
	</tr>
	<% end %>
</table>

app/views/admins/users/show.html.erb
<h2>ユーザー詳細</h2>
<table>
	<tr>
		<th>ID</th>
		<th>おなまえ（漢字</th>
		<th>おなまえ（カタカナ）</th>
		<th>メールアドレス</th>
		<th>携帯番号</th>
		<th>郵便番号</th>
		<th>都道府県</th>
		<th>住所</th>
		<th>建物</th>
	</tr>

	<tr>
		<td><%= @user.id %></td>
		<td><%= @user.name_char %></td>
		<td><%= @user.name_kana %></td>
		<td><%= @user.email %></td>
		<td><%= @user.tell %></td>
		<td><%= @user.post %></td>
		<td><%= @user.address_prefecture %></td>
		<td><%= @user.address_city %></td>
		<td><%= @user.address_building %></td>
	</tr>
</table>

<h2>ユーザー履歴</h2>
<table>
    <tr>
        <th>日付</th>
        <th>時間</th>
        <th>発送ステータス</th>
        <th>ID</th>
        <th></th>
    </tr>
    <% @histories.each do |h| %>
        <tr>
            <td><%= h.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= h.created_at.strftime('%H:%M') %></td>
            <td>
                <%= form_for(h, url: admins_history_path(h), method: :patch) do |f| %>
                    <%= f.select :status, [["1.準備中", 1], ["2.発送中", 2], ["3.発送済", 3]], prompt: "1.準備中", selected: h.status %>
                    <%= f.submit "変更を保存" %>
                <% end %>
            </td>
            <td><%= link_to h.user_id, admins_user_path(h.user_id) %></td>
            <td><%= link_to "詳細", admins_history_path(h.id) %></td>
        </tr>
    <% end %>
</table>